# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d73e0ec75ee935611198ffcdc208acf56a2fb7dcaea39eeee795d5e53c2b98174bb4e3a9d03ebf07eddfb4822f74e6dc782014b0a4fb02ed724f327e2ec1be0

test:
  secret_key_base: d6e7e25a391b9ad55dd8e43f3ce0420ae29c3f0fbc70ae4d2442c4f8b47158b069aa640aa9673e250939e03ea2b4c540515843038474fd36c518cb3b414d3d1c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
